### ISSUE TITLE
In included file: too few arguments provided to function-like macro invocation

### ISSUE THREAD

**Issue by Season0518** [FeignClaims/cpp_conan_template#1]
<img width="1155" alt="image" src="https://github.com/FeignClaims/cpp_conan_template/assets/30144502/0a954843-e38a-4ddf-af6a-3138afa56dc6">

After I configured gcc-13 and conan according to Configure option 2: invoice conan, then cmake, it prompted "In included file: too few arguments provided to function like macro invoice". Why is this?

OS: macOS 14.4.1 23E224 arm64

SDK:
xcode-select: version 2406
gcc: gcc-13 (Homebrew GCC 13.2.0) 13.2.0
clangd: Homebrew clangd version 18.1.5
XCode: 15.3 (SDKVersion 14.4)

**Comment by FeignClaims** [comment]
I'm also using macos and encountered this problem before. This actually is something about your clangd extension configuraiton or your gcc installation.

The possible solution is:

- Configure your vscode clangd extension, add `--query-driver=path_pattern_1,...,path_pattern_n` option to specify the compiler path.
- Since gcc has released 14 today (or yesterday maybe?), it's a fairly good time to run `brew upgrade --greedy` to upgrade gcc.

<img width="731" alt="image" src="https://github.com/FeignClaims/cpp_conan_template/assets/62583114/99d42cc6-1ba1-451a-8179-751977b7c10c">

In addition, there's [a link issue in homebrew llvm]() that might be related to this problem. Could you show me your conan gcc profile by `cat $(conan profile path <profile_name>)`? Here my profile by the way:

<details>
<summary>_common</summary>

```
[conf]
tools.build:cflags=['-L/opt/homebrew/opt/llvm/lib/c++', '-Wno-unused-command-line-argument']
tools.build:cxxflags=['-L/opt/homebrew/opt/llvm/lib/c++', '-Wno-unused-command-line-argument']
&:tools.cmake.cmake_layout:build_folder_vars=['settings.compiler']
&:tools.cmake.cmaketoolchain:generator=Ninja Multi-Config
```
</details>

<details>
<summary>gcc</summary>

```
include(_common)

[settings]
arch=armv8
build_type=Release
compiler=gcc
compiler.cppstd=23
compiler.libcxx=libstdc++11
compiler.version=14
os=Macos

[conf]
tools.build:compiler_executables = {"c": "/opt/homebrew/bin/gcc-14", "cpp": "/opt/homebrew/bin/g++-14"}
```
</details>

**Comment by FeignClaims** [comment]
It seems like you're using my VSCode configuration tutorial? If that's the case, the appendix actually has shown how to set `--query-driver=path_pattern_1,...,path_pattern_n` [here](https://vscode-cpp-starter.readthedocs.io/appendix/choose_compiler/main.html).

**Comment by Season0518** [comment]
First of all, thank you for your prompt answer.

I just solved this problem by downgrading the XCode version. I downgraded the XCode version to 15.0 and the problem was solved. In fact, this problem was originally caused by updating XCode.

<img width="739" alt="image" src="https://github.com/FeignClaims/cpp_conan_template/assets/30144502/543c5625-bea0-4e01-8bc4-c0660e8e7a76">

For the solution you mentioned, I will try it in the virtual machine to see if it can be solved

**Comment by Season0518** [comment]
> It seems like you're using my VSCode configuration tutorial? If that's the case, the appendix actually has shown how to set `--query-driver=path_pattern_1,...,path_pattern_n` [here](https://vscode-cpp-starter.readthedocs.io/appendix/choose_compiler/main.html).

In fact, I wrote my own XMake-based version inspired by your VSCode configuration tutorial. 

Because I wanted to get help, I used your configuration to reproduce the entire error when I encountered this error.

**Comment by Season0518** [comment]
Thank you for your solution.

 In fact, this problem can be easily solved through `brew upgrade gcc -- greedy`.

I have tested it on different computers (physical and virtual), and in fact, upgrading the gcc version is a simple and effective solution.

Finally, Here is my config: [Season0518/MyConfig](https://github.com/Season0518/MyConfig). Based on XMake, simplified configuration and minimized network connections as much as possible.

**Comment by FeignClaims** [comment]
> In fact, this problem can be easily solved through `brew upgrade gcc --greedy`.

To clarify, the issue might be caused by the update of XCode as you mentioned. Just executing `brew reinstall gcc` should be enough to solve this problem, as I did before.

I was too lazy to mention this. Sorry for the misleading.
